### ISSUE TITLE
Windows 7 x64 启动白屏

### ISSUE THREAD

**Issue by xiaokaixuan** [Cyenoch/Flutter-Coolapk#10]

**Comment by Cyenoch** [comment]
**请先尝试以下方法:**
如果出现打开后白屏的问题，请删除该目录下的所有文件： (win10下Users显示为 "用户")
C:\Users(可能名称"用户")\你的系统用户名\AppData\Local\Temp\flutter_coolapk
(AppData目录是隐藏目录, [win7查看隐藏目录教程](https://jingyan.baidu.com/article/59a015e31621b9f7948865c5.html))

**Comment by xiaokaixuan** [comment]
这方法一开始就试过了。可能是我系统的问题，很久没更新过也没打过补丁。

**Comment by Cyenoch** [comment]
我也没win7可以测试...也没做全局异常捕捉,没写log...... 失策
