### ISSUE TITLE
点赞数显示不正常（其实这一排几个按钮都无效）；打不开应用集；查看应用评价会提示 不支持的content type5

### ISSUE THREAD

**Issue by hoixding** [Cyenoch/Flutter-Coolapk#7]
![image](https://user-images.githubusercontent.com/32367628/87083991-100a9780-c260-11ea-82e7-11bb8eee8568.png)
![image](https://user-images.githubusercontent.com/32367628/87084103-447e5380-c260-11ea-80af-1c16c350ef18.png)

**Comment by Cyenoch** [comment]
不支持的content type说明我还为对这个内容做适配... 应用集还没做。点赞数显示不正常其实可以忽略。 分享按钮没做
